### ISSUE TITLE
External Power Switch Question

### ISSUE THREAD

**Issue by devax** [michaelwittig/hoerbox#1]
Great project, thank you for sharing! I'm trying to build something similar for my kids. Could you share some more information about how you have connected the external power switch?

**Comment by michaelwittig** [comment]
Sorry for missing your comment. The external power switch turns off the battery connection. 
Downside: To charge the battery, you have to turn on the switch (and therefore the device)
Upside: I can be certain that the device is 100% powered off :)

I'm very interested in your progress. I plan to build a 2nd box this year.

**Comment by devax** [comment]
Thank you very much for your feedback! Unfortunately, I had to capitulate with this project. My ambitions were too high compared to my (C) skills. Eventually, I built a Raspberry Pi-based box (phoniebox) which was a lot easier for me and luckily worked out.

**Comment by michaelwittig** [comment]
I'm happy to hear that you completed the project :)
